version: '3.8'
services:
  anime-kun-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: anime_user
      POSTGRES_PASSWORD: anime_password
      POSTGRES_DB: anime_kun
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - anime-kun-postgres
    ports:
      - "3001:3000"
    volumes:
      - ./api:/app
      - ./api/uploads:/app/uploads
    environment:
      - DB_HOST=anime-kun-postgres
      - DB_USER=anime_user
      - DB_PASSWORD=anime_password
      - DB_NAME=anime_kun
      - DB_PORT=5432
      - PORT=3000
      - NODE_ENV=development
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - API_BASE_URL=http://api:3000
volumes:
  db_data:
  uploaded_images: