// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/6/2025, 10:12:24 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/zohardus/www/ak9project/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontend/plugins/**/*.{js,ts,mjs}","/home/zohardus/www/ak9project/frontend/composables/**/*.{js,ts,mjs}","/home/zohardus/www/ak9project/frontend/utils/**/*.{js,ts,mjs}","/home/zohardus/www/ak9project/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/zohardus/www/ak9project/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;